title: Zhiheng (Caroline) Li's Homepage
page-top-title: Zhiheng(Caroline)
top-section-bg-text: Computer Science
home-subtitle: Zhiheng Li (she/they)
copyright-text: '&copy; Zhiheng Li 2025. All Rights Reserved. Portfolio Template by Sen Li'