title: Zhiheng(Caroline) Li's Homepage
page-top-title: Zhiheng(Caroline)
top-section-bg-text: Computer Science
home-subtitle: Zhiheng Li&ensp;|&ensp;Caroline
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
